language: c

script: echo "\documentclass{article}\begin{document}\end{document}" | pdflatex

before_install:
  - date
  - curl -L https://github.com/krlmlr/texlive-squashfs/raw/master/out/texlive.tar.xz | tar -JxC ~
  - date

install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH

notifications:
  email:
    on_success: change
    on_failure: always
