language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - p7zip-full
script:
- bash download.sh
#- travis_wait 60 bash prepare_onlyEN.sh
- travis_wait 60 bash prepare.sh
deploy:
  provider: releases
  user: ${GITHUB_USERNAME}
  password: ${GITHUB_PASSWORD}
  file:
    - texlive.tar.xz
#    - texlive_onlyEN.tar.xz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
