language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - p7zip-full
script:
- bash download.sh
- travis_wait 60 bash prepare.sh
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - texlive.tar.xz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
