language: c

script: echo | pdflatex

before_install:
  - curl -OL https://github.com/krlmlr/texlive-squashfs/raw/master/out/texlive.squashfs

install:
  - unsquashfs -d ~/texlive texlive.squashfs
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH

notifications:
  email:
    on_success: change
    on_failure: always
